pipeline {
    agent none
    options {
      	skipDefaultCheckout()
  		disableConcurrentBuilds()
    }

    stages {

      stage('docker-build'){
          agent any

                steps  {

                        checkout scm
                        sh ''' pwd
                         cd rails_api
                         pwd 
                         make docker-build '''

                }
      }

    }

}
