---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: express-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: express-api
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: express-api
    spec:
      containers:
      - image: 861276100864.dkr.ecr.ap-south-1.amazonaws.com/express-api:latest
        imagePullPolicy: Always
        name: express-api
        ports:
        - containerPort: 4001
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: express-api-hpa
  namespace: prod
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: express-api
  targetCPUUtilizationPercentage: 75
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: express-api-service
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4001
  selector:
    app.kubernetes.io/name: express-api
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-api-service
  namespace: prod
spec:
  ingressClassName: nginx
  rules:
  - host: kotak-test.expressapi.com
    http:
      paths:
      - backend:
          service:
            name: express-api-service
            port:
              number: 80
        path: /
        pathType: Prefix
