---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: rails-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rails-api
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rails-api
    spec:
      containers:
      - image: 940937972577.dkr.ecr.ap-south-1.amazonaws.com/rails-api:latest
        imagePullPolicy: Always
        name: rails-api
        ports:
        - containerPort: 3000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: rails-api-hpa
  namespace: prod
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: rails-api
  targetCPUUtilizationPercentage: 80
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: rails-api-service
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/name: rails-api
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rails-api-service
  namespace: prod
spec:
  ingressClassName: nginx
  rules:
  - host: kotak-test.railsapi.com
    http:
      paths:
      - backend:
          service:
            name: rails-api-service
            port:
              number: 80
        path: /
        pathType: Prefix
